### ISSUE TITLE
Some mistakes

### ISSUE THREAD

**Issue by Athenacle** [DmitryHetman/gentoofetch.sh#1]
Here is my output.
![gf](https://cloud.githubusercontent.com/assets/1025054/25199389/4aee3898-2510-11e7-9303-28d7ad6e0c19.png)

1. Get my sound card failed.  'grep -m1 PCH /proc/asound/cards' return nothing. However, after get infomation failed, you should redirect the stderr to /dev/null and treat the sound card as "unknown", instead of printing  'grep: /proc/asound/card/codec#*: No such file or directory'
2. Get my root partition error. Root: 0/3.9G devtmpfs??
3. Intel GPU?  I use NVIDIA GTX650 and nouveau. Why you tell me 'Intel HD Graphics'?
![ter](https://cloud.githubusercontent.com/assets/1025054/25199982/55a3b360-2512-11e7-9e9b-4cefe450616f.png)

**Comment by DmitryHetman** [comment]
Thanks for help, GPU detection not ready yet, only works for intel.
Root detection will be fixed now.

**Comment by DmitryHetman** [comment]
Soundcard detection will be fixed soon.

**Comment by DmitryHetman** [comment]
@Athenacle Here is output of script after fixes, should I remove comma and add semicolon instead?
![wayland-screenshot](https://cloud.githubusercontent.com/assets/18743742/25229913/bc33ca34-25c1-11e7-95fa-190dbd5cc00d.png)
